# Form implementation generated from reading ui file 'ELO.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(961, 747)
        self.iq = QtWidgets.QLabel(parent=Dialog)
        self.iq.setGeometry(QtCore.QRect(360, 80, 311, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.iq.setFont(font)
        self.iq.setObjectName("iq")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(350, 240, 291, 121))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.ButtonClick = QtWidgets.QPushButton(parent=Dialog)
        self.ButtonClick.setGeometry(QtCore.QRect(360, 630, 291, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ButtonClick.setFont(font)
        self.ButtonClick.setObjectName("ButtonClick")
        self.lineEditIQ = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditIQ.setGeometry(QtCore.QRect(380, 140, 231, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditIQ.setFont(font)
        self.lineEditIQ.setObjectName("lineEditIQ")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.iq.setText(_translate("Dialog", "ILE MASZ IQ?"))
        self.ButtonClick.setText(_translate("Dialog", "--> gorace mamuski <--"))
